spring:
  application:
    name: devjarvis-backend

  datasource:
    url: jdbc:postgresql://devjarvis-postgres:5432/devjarvis
    username: devjarvis
    password: "${DEVJARVIS_DB_PASSWORD}"
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false

server:
  port: 8080
